Unit tests and image scanner
canonical/identity-platform-login-ui pull request #12
Opened 2023-02-20 15:15 UTC by bencekov

This pr includes the currently unfinished unit tests, and the updated github workflow with container image scanning with trivy.

2023-02-20 20:11 UTC, massimilianogo commented
@bencekov please split the build.yaml workflow in smaller workloads which perform one action only (e.g. build, test, scan, publish)
You can refer to [this PR](https://github.com/canonical/nginx-rock/pull/4) as an example.

2023-02-21 13:57 UTC, gruyaume commented on main_test.go
> +package main
I don't see the place in the CI where those are executed, please make sure they at least run on every PR.

2023-02-21 14:19 UTC, nsklikas requested changes
Good job. I have a couple of comments:
- The tests need to check that the serve behaves as expected when errors occur as well. For every endpoint we need to check what happens if we get an unexpected response from kratos/hydra. 
- We need to test what will happen if the server gets a bad/malformed parameter in the request. 
- Are you going to implement the rest of the server mock responses in this PR or is it going to be done in another one?

2023-02-21 14:19 UTC, nsklikas commented on main_test.go
> +	hydraClient := CreateHydraMockServer()
This will happen in every test, let's move it to a `setup` function.

2023-02-24 05:20 UTC, closed without merging