fix ui for totp setup screen, add separators
canonical/identity-platform-login-ui pull request #325
Opened 2024-10-11 13:47 UTC by edlerd

# Done
- fix ui for totp setup screen, add separators

fixes #324

2024-10-11 14:07 UTC, nsklikas approved these changes

2024-10-11 14:14 UTC, natalian98 approved these changes

2024-10-11 14:39 UTC, natalian98 requested changes
Could you also change the wording to address Lukas' comment?
We have:
![image](https://github.com/user-attachments/assets/4e68dfaa-8eab-4888-9579-4cfb18575bc1)
We'd like to have:
![image](https://github.com/user-attachments/assets/1a4a3841-389f-41e7-841f-6706a2cdb630)

2024-10-11 17:24 UTC, edlerd commented
> Could you also change the wording to address Lukas' comment?

I assume this is kratos configuration? Because the text is coming from the UI nodes of the kratos flow.

2024-10-14 08:56 UTC, natalian98 commented
> Can you configure this in Kratos @natalian98 ? As the UI is not in control of the copy.

This is not configurable in kratos, but I assumed you can change the ui nodes values in the frontend. If that's not possible, let's leave it in the current state.

2024-10-14 10:48 UTC, edlerd commented
Amended the PR to handle also the special copy.

2024-10-14 11:31 UTC, natalian98 commented on ui/components/NodeText.tsx
> +            provided on-time code
```suggestion
            provided one-time code
```

2024-10-14 12:42 UTC, nsklikas reviewed
This looks fine, but I have some concerns with this approach. It feels like the mapping of custom texts to our own logic is bound to get our of hand. I think that we should:
- Invest some time to evaluate if we can have a more generalized approach to mapping so that the mapping logic is centralized somewhere
- Instead of mapping text to text, we should map attribute_id to text. For example: 
Change `const isTotpQrCode = node.meta.label?.text === "Authenticator app QR code";` to `const isTotpQrCode = node.attributes.id === totp_qr` and 
```
  const isTotpSetup =
    node.meta.label?.text ===
    "This is your authenticator app secret. Use it if you can not scan the QR code.";
``` 
to `const isTotpSetup = node.attributes.id === "totp_secret_key";`
The problem with using the text as an id is that on update the text might change, but IDs are way less likely to change

2024-10-14 13:00 UTC, edlerd commented on ui/components/NodeText.tsx
> +            provided on-time code
whoopsie.

2024-10-14 13:01 UTC, edlerd commented
> This looks fine, but I have some concerns with this approach. It feels like the mapping of custom texts to our own logic is bound to get our of hand. I think that we should:

Totally agree, wasn't aware of those stable text ids, which are much better to target. Changed the approach.

2024-10-14 13:59 UTC, nsklikas approved these changes

2024-10-14 15:10 UTC, nsklikas approved these changes

2024-10-15 08:42 UTC, natalian98 approved these changes

2024-10-15 08:42 UTC, merged